return {
    noId = 'Debes introducir un ID válido',
    idNoExist = 'El ID proporcionado no existe',
    mutedPlayer = 'ha sido silenciado',
    muted = 'Un administrador te ha silenciado, no podrás chatear',
    mutedText = 'Tus mensajes no llegarán a otros usuarios porque te han silenciado',
    unmuted = 'Un administrador ha desactivado tu silencio, ahora puedes chatear',
    muteMsg = 'Silenciado',
    muteMsgTitle = 'Silenciado',
    muteHelpTitle = 'Silenciar a un jugador',
    muteHelpName = 'id',
    muteHelpText = 'ID del jugador a silenciar',
    unmutedPlayer = 'ha sido desactivado el silencio',
    unmuteHelpTitle = 'Desactivar el silencio a un jugador',
    unmuteHelpName = 'id',
    unmuteHelpText = 'ID del jugador al que desactivar el silencio',
    noMoney = 'Dinero insuficiente',
    cooldown = 'Tienes que esperar para enviar otro mensaje',
    plydisconnected = 'Este ID no está conectado',
    pmTo = 'MSG para [ %s ]',
    pmFrom = 'MSG de [ %s ]',
    dicesTitle = '[ %s ][ Dados ]',
    staffChat = '[ %s ] [STAFF]',
    tryCommand = '[%s] [Suerte]'
}
